name: Build & Push Docker Image

on:
  push:
    branches: [master]
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  publish:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    permissions:
      contents: write  # required to push tag
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Create semantic version tag
        id: tagger
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master
          tag_prefix: "v"
          default_bump: patch

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define image name
        id: meta
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          IMAGE_NAME="${IMAGE_NAME,,}"  # lowercase
          echo "name=$IMAGE_NAME" >> "$GITHUB_OUTPUT"
          echo "version=${{ steps.tagger.outputs.new_tag }}" >> "$GITHUB_OUTPUT"

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ steps.meta.outputs.name }}:latest .
          docker tag ${{ steps.meta.outputs.name }}:latest ${{ steps.meta.outputs.name }}:${{ steps.meta.outputs.version }}

      - name: Push Docker images
        run: |
          docker push ${{ steps.meta.outputs.name }}:latest
          docker push ${{ steps.meta.outputs.name }}:${{ steps.meta.outputs.version }}
